#include "stepMotor.h"


void stepMotor_Stop(void) {
	HAL_TIM_Base_Stop_IT(&htim4);
	HAL_GPIO_WritePin(STEP_A1_GPIO, STEP_A1_GPIO_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(STEP_B1_GPIO, STEP_B1_GPIO_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(STEP_A2_GPIO, STEP_A2_GPIO_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(STEP_B2_GPIO, STEP_B2_GPIO_PIN, GPIO_PIN_RESET);
}

void stepMotor_Run(void) {
	HAL_TIM_Base_Start_IT(&htim4);
}


void stepMotor_CCW() {
	static uint8_t stepMotor_phase = 0;
	stepMotor_phase = (stepMotor_phase + 1) % 4;
	switch(stepMotor_phase) {
		case 0:
			HAL_GPIO_WritePin(STEP_A1_GPIO, STEP_A1_GPIO_PIN, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(STEP_B1_GPIO, STEP_B1_GPIO_PIN, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(STEP_A2_GPIO, STEP_A2_GPIO_PIN, GPIO_PIN_SET);
			HAL_GPIO_WritePin(STEP_B2_GPIO, STEP_B2_GPIO_PIN, GPIO_PIN_SET);
			break;
		case 1:
			HAL_GPIO_WritePin(STEP_A1_GPIO, STEP_A1_GPIO_PIN, GPIO_PIN_SET);
			HAL_GPIO_WritePin(STEP_B1_GPIO, STEP_B1_GPIO_PIN, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(STEP_A2_GPIO, STEP_A2_GPIO_PIN, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(STEP_B2_GPIO, STEP_B2_GPIO_PIN, GPIO_PIN_SET);
			break;
		case 2:
			HAL_GPIO_WritePin(STEP_A1_GPIO, STEP_A1_GPIO_PIN, GPIO_PIN_SET);
			HAL_GPIO_WritePin(STEP_B1_GPIO, STEP_B1_GPIO_PIN, GPIO_PIN_SET);
			HAL_GPIO_WritePin(STEP_A2_GPIO, STEP_A2_GPIO_PIN, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(STEP_B2_GPIO, STEP_B2_GPIO_PIN, GPIO_PIN_RESET);
			break;
		case 3:
			HAL_GPIO_WritePin(STEP_A1_GPIO, STEP_A1_GPIO_PIN, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(STEP_B1_GPIO, STEP_B1_GPIO_PIN, GPIO_PIN_SET);
			HAL_GPIO_WritePin(STEP_A2_GPIO, STEP_A2_GPIO_PIN, GPIO_PIN_SET);
			HAL_GPIO_WritePin(STEP_B2_GPIO, STEP_B2_GPIO_PIN, GPIO_PIN_RESET);
			break;
	}
}

void stepMotor_CW() {
	static uint8_t stepMotor_phase = 0;
		stepMotor_phase = (stepMotor_phase + 1) % 4;
		switch(stepMotor_phase) {
			case 0:
				HAL_GPIO_WritePin(STEP_A1_GPIO, STEP_A1_GPIO_PIN, GPIO_PIN_RESET);
				HAL_GPIO_WritePin(STEP_B1_GPIO, STEP_B1_GPIO_PIN, GPIO_PIN_SET);
				HAL_GPIO_WritePin(STEP_A2_GPIO, STEP_A2_GPIO_PIN, GPIO_PIN_SET);
				HAL_GPIO_WritePin(STEP_B2_GPIO, STEP_B2_GPIO_PIN, GPIO_PIN_RESET);
				break;
			case 1:
				HAL_GPIO_WritePin(STEP_A1_GPIO, STEP_A1_GPIO_PIN, GPIO_PIN_SET);
				HAL_GPIO_WritePin(STEP_B1_GPIO, STEP_B1_GPIO_PIN, GPIO_PIN_SET);
				HAL_GPIO_WritePin(STEP_A2_GPIO, STEP_A2_GPIO_PIN, GPIO_PIN_RESET);
				HAL_GPIO_WritePin(STEP_B2_GPIO, STEP_B2_GPIO_PIN, GPIO_PIN_RESET);
				break;
			case 2:
				HAL_GPIO_WritePin(STEP_A1_GPIO, STEP_A1_GPIO_PIN, GPIO_PIN_SET);
				HAL_GPIO_WritePin(STEP_B1_GPIO, STEP_B1_GPIO_PIN, GPIO_PIN_RESET);
				HAL_GPIO_WritePin(STEP_A2_GPIO, STEP_A2_GPIO_PIN, GPIO_PIN_RESET);
				HAL_GPIO_WritePin(STEP_B2_GPIO, STEP_B2_GPIO_PIN, GPIO_PIN_SET);
				break;
			case 3:
				HAL_GPIO_WritePin(STEP_A1_GPIO, STEP_A1_GPIO_PIN, GPIO_PIN_RESET);
				HAL_GPIO_WritePin(STEP_B1_GPIO, STEP_B1_GPIO_PIN, GPIO_PIN_RESET);
				HAL_GPIO_WritePin(STEP_A2_GPIO, STEP_A2_GPIO_PIN, GPIO_PIN_SET);
				HAL_GPIO_WritePin(STEP_B2_GPIO, STEP_B2_GPIO_PIN, GPIO_PIN_SET);
				break;
		}
}
